apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
data:
  user: YWRtaW4= # echo -n "admin" | base64
  password: cGFzc3dvcmQ= # echo -n "password" | base64
  root-password: cGFzc3dvcmQ= # echo -n "password" | base64
